name: silverguard
description: "SDK Flutter para integração com o fluxo de **Contestação CAM** da Silverguard."
version: 0.0.1
homepage: https://www.silverguard.com.br/

#developed on flutter 3.35.2
environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: 4.11.0
  permission_handler: 12.0.0+1
  http: 1.5.0
  file_picker: 10.3.2 
  alchemist: 0.12.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4


flutter:  
  uses-material-design: true

